// @ts-check
// Barra lateral autogenerada a partir de la estructura de carpetas de /docs.
// No hay que editar este archivo al añadir documentos: basta con crear
// carpetas y ficheros .md. El orden se controla con un `_category_.json`
// en cada carpeta o con `sidebar_position` en el frontmatter de cada doc.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  principal: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
